version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: activerecord
    versions:
    - 6.1.2.1
    - 6.1.3
  - dependency-name: jekyll-feed
    versions:
    - 0.15.1
