name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Prepare environment
      run: |
        sudo apt install libsqlite3-dev -y && \
        sudo gem install pluto bundler && \
        sudo sed 's|rexml/D|rexml/d|' -i /var/lib/gems/2.5.0/gems/opmlparser-1.0.0/lib/opmlparser.rb
    - uses: actions/checkout@v2
    - name: Fetch feeds
      run: pluto u planet.ini
    - name: Build the site
      run: sudo bundle install && bundle exec jekyll build --future
    - name: Publish generated content to GitHub Pages
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.0
      with:
        dir: _site
        branch: gh-pages
        token: ${{ secrets.ACCESS_TOKEN }}
