name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Prepare environment
      run: |
        sudo apt install libsqlite3-dev -y && \
        sudo gem install pluto bundler
    - uses: actions/checkout@v2
    - name: Fetch feeds
      run: pluto u planet.ini
    - name: Build the site
      run:  bundle exec jekyll build --future
