name: Jekyll site CI

on:
  schedule:
    - cron: '0 */2 * * *'
  push:
    branches: [gh-pages]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Prepare environment
      run: |
        sudo apt update && \
        sudo apt install libsqlite3-dev -y && \
        sudo gem install pluto bundler
    - uses: actions/checkout@v2
    - name: Fetch feeds
      run: pluto u planet.ini
    - name: Build the site
      run: sudo bundle install && bundle exec jekyll build --future
    - name: Publish generated content to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: master
        build_dir: _site
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
